# Copyright (c) 2022 Omada Community Developers
name: omada
base: core20
version: 5.3.1
summary: Software Defined Networking (SDN) with Cloud Access
description: |
  Omada’s Software Defined Networking (SDN) platform integrates
  network devices, including access points, switches and 
  gateways, providing 100% centralized cloud management.
  Omada creates a highly scalable network—all controlled from
  a single interface. Seamless wireless and wired connections
  are provided, ideal for use in hospitality, education, retail,
  offices, and more.
  
  Documentation and wiki:
  
  - Business Community: https://community.tp-link.com/business/
  - TP-Link Support:    https://www.tp-link.com/support/
  
  Omada Logo source:
  https://static.tp-link.com/res/images/static/omada/images/logo.png
grade: devel
confinement: strict
icon: src/omada.png
apps:
  tpeap:
    command: opt/tplink/EAPController/bin/control.sh
    plugs: [network, network-bind, network-status, home, removable-media, root]
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-1.8.0-openjdk-amd64
      PATH: $JAVA_HOME/bin:$JAVA_HOME/jre/bin:$SNAP/usr/bin:$SNAP/opt/tplink/EAPController/bin:$PATH
parts:
  add-ppa:
    plugin: nil
    override-pull: |
      echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb.list
      apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 656408E390CFB1F5
      apt update
      apt upgrade -yy
    build-packages:
      - software-properties-common
      - dirmngr
      - gnupg
      - apt-transport-https
      - ca-certificates
  tpeap:
    after: [add-ppa]
    source: https://static.tp-link.com/upload/software/2022/202205/20220507/Omada_SDN_Controller_v${SNAPCRAFT_PROJECT_VERSION}_Linux_x64.deb
    source-type: deb
    plugin: dump
    stage-packages:
      - adduser
      - jsvc
      - curl
      - openjdk-8-jre-headless
      - mongodb-org